server:
    port: 8080
spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/cleanstock
        username: root
    jpa:
        hibernate:
            ddl-auto: update
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                naming:
                    physical-strategy: com.bortoti.cleanstock.adapter.out.config.CustomNamingStrategy
        show-sql: true