server:
    port: 8080
spring:
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/cleanstock
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
